package soroauth

import (
	"bytes"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stellar/go-stellar-sdk/xdr"
)

// differentialCorpusDir is where cmd/difffuzz writes the committed corpus. The
// corpus is generated, so it is never edited by hand: regenerate it with
// `go run ./cmd/difffuzz`, and CI fails on drift the same way it does for the
// golden vectors.
const differentialCorpusDir = "testdata/differential/corpus"

// differentialRegressionsDir holds cases that diverged once and were frozen as
// reproducers (`go run ./cmd/difffuzz -freeze <case>`). They are checked by the
// same tests and the same verifiers as the swept corpus, so a divergence stays
// covered even after the sweep's seed moves.
const differentialRegressionsDir = "testdata/differential/regressions"

// differentialSchemaVersion is the only corpus schema this reader understands.
// A reader that guessed at an unknown version would be comparing fields that
// may have moved.
const differentialSchemaVersion = 1

// differentialCase is one generated entry and what this library derived from
// it. The field names are the ones cmd/difffuzz writes and the two
// cross-implementation verifiers read.
type differentialCase struct {
	SchemaVersion     int    `json:"schema_version"`
	Name              string `json:"name"`
	Generator         string `json:"generator"`
	Seed              uint64 `json:"seed"`
	Index             int    `json:"index"`
	CredentialArm     string `json:"credential_arm"`
	NetworkPassphrase string `json:"network_passphrase"`
	ValidUntilLedger  uint32 `json:"valid_until_ledger"`
	UnsignedEntryXDR  string `json:"unsigned_entry_xdr"`
	PreimageXDR       string `json:"preimage_xdr"`
	PayloadHex        string `json:"payload_hex"`
}

func loadDifferentialCorpus(t testing.TB) []differentialCase {
	t.Helper()

	var paths []string
	for _, dir := range []string{differentialCorpusDir, differentialRegressionsDir} {
		found, err := filepath.Glob(filepath.Join(dir, "*.json"))
		if err != nil {
			t.Fatalf("globbing %s: %v", dir, err)
		}
		paths = append(paths, found...)
	}
	// Without this, deleting the corpus would turn every test here into one
	// that passes by doing nothing.
	if len(paths) == 0 {
		t.Fatalf("no differential corpus found in %s; run `go run ./cmd/difffuzz`", differentialCorpusDir)
	}

	cases := make([]differentialCase, 0, len(paths))
	for _, path := range paths {
		raw, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("reading %s: %v", path, err)
		}
		var doc differentialCase
		// Unknown fields are rejected so a generator change cannot be silently
		// half-read by this side.
		decoder := json.NewDecoder(bytes.NewReader(raw))
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&doc); err != nil {
			t.Fatalf("decoding %s: %v", path, err)
		}
		if doc.SchemaVersion != differentialSchemaVersion {
			t.Fatalf("%s has unsupported schema version %d, want %d",
				path, doc.SchemaVersion, differentialSchemaVersion)
		}
		if !strings.HasPrefix(doc.Generator, "cmd/difffuzz") {
			t.Fatalf("%s was generated by %q, want cmd/difffuzz", path, doc.Generator)
		}
		if doc.Name == "" {
			t.Fatalf("%s has no name", path)
		}
		if doc.Name != caseStem(filepath.Base(path)) {
			t.Fatalf("%s is named %q, want %q", path, doc.Name, caseStem(filepath.Base(path)))
		}
		cases = append(cases, doc)
	}
	return cases
}

// caseStem strips the .json extension from a case file name.
func caseStem(name string) string {
	return name[:len(name)-len(".json")]
}

// decodeDifferentialEntry decodes a case's unsigned entry.
func decodeDifferentialEntry(t testing.TB, doc differentialCase) xdr.SorobanAuthorizationEntry {
	t.Helper()
	var entry xdr.SorobanAuthorizationEntry
	if err := xdr.SafeUnmarshalBase64(doc.UnsignedEntryXDR, &entry); err != nil {
		t.Fatalf("%s: decoding the unsigned entry: %v", doc.Name, err)
	}
	return entry
}

// recomputeDifferential returns this library's preimage and payload for a case,
// or an empty result for the source-account arm, which has no preimage
// (CAP-46-11; the transaction envelope authenticates it instead).
func recomputeDifferential(t testing.TB, doc differentialCase) (preimageXDR, payloadHex string) {
	t.Helper()
	entry := decodeDifferentialEntry(t, doc)

	preimage, err := Preimage(entry, doc.ValidUntilLedger, doc.NetworkPassphrase)
	if err != nil {
		if doc.CredentialArm == "source_account" {
			// Expected for this arm; the corpus records nothing for it, and
			// the first argument of this test asserts that.
			return "", ""
		}
		t.Fatalf("%s: building the preimage: %v", doc.Name, err)
	}

	encoded, err := preimage.MarshalBinary()
	if err != nil {
		t.Fatalf("%s: encoding the preimage: %v", doc.Name, err)
	}
	payload, err := Payload(preimage)
	if err != nil {
		t.Fatalf("%s: hashing the preimage: %v", doc.Name, err)
	}
	return base64.StdEncoding.EncodeToString(encoded), hex.EncodeToString(payload[:])
}

// differentialProblems compares a recomputed preimage and payload against the
// recorded ones and returns a description of every disagreement. It is the same
// comparison the JS and Python verifiers perform, expressed once here so the
// negative control below can prove it bites.
func differentialProblems(wantPreimageXDR, wantPayloadHex, gotPreimageXDR, gotPayloadHex string) []string {
	var problems []string
	if gotPreimageXDR != wantPreimageXDR {
		problems = append(problems, "preimage differs")
	}
	if gotPayloadHex != wantPayloadHex {
		problems = append(problems, "payload differs")
	}
	return problems
}

// TestDifferentialCorpusRecomputes is the drift guard on the committed corpus:
// every recorded preimage and payload must be what this library derives from the
// entry today. If Preimage changes, the corpus is stale and this fails until it
// is regenerated, which is what keeps the corpus a description of the current
// wire format rather than of an old one.
//
// This side alone cannot prove agreement is *correct*: the corpus was recorded
// by this same library, so a bug here would be recorded too. That is what the
// other two implementations are for. testdata/differential/verify.mjs
// recomputes every case with @stellar/stellar-sdk and
// testdata/parity-python/parity.py does it with the Python stellar-sdk; the two
// together make the comparison three-way. `make differential` and the CI parity
// matrix run them.
func TestDifferentialCorpusRecomputes(t *testing.T) {
	for _, doc := range loadDifferentialCorpus(t) {
		t.Run(doc.Name, func(t *testing.T) {
			gotPreimage, gotPayload := recomputeDifferential(t, doc)

			if doc.CredentialArm == "source_account" {
				// A source-account entry has no preimage, so the corpus must
				// record neither value, and the verifiers must skip it rather
				// than compare against something invented.
				if doc.PreimageXDR != "" || doc.PayloadHex != "" {
					t.Errorf("source-account case records preimage %q / payload %q, want both empty",
						doc.PreimageXDR, doc.PayloadHex)
				}
				if gotPreimage != "" || gotPayload != "" {
					t.Errorf("Preimage produced %q / %q for a source-account entry, want an error",
						gotPreimage, gotPayload)
				}
				return
			}

			if problems := differentialProblems(doc.PreimageXDR, doc.PayloadHex, gotPreimage, gotPayload); len(problems) > 0 {
				t.Errorf("recorded payload no longer matches this library: %v\n  recorded preimage %s\n    recomputed    %s\n  recorded payload  %s\n    recomputed      %s",
					problems, doc.PreimageXDR, gotPreimage, doc.PayloadHex, gotPayload)
			}
		})
	}
}

// TestDifferentialRecomputationDetectsTampering is the negative control. If a
// recorded payload could be wrong without the comparison noticing, the
// comparison would be decoration; this flips one byte of a recorded payload and
// requires the same comparison the verifiers use to report it.
func TestDifferentialRecomputationDetectsTampering(t *testing.T) {
	cases := loadDifferentialCorpus(t)

	var target *differentialCase
	for i := range cases {
		if cases[i].CredentialArm == "address_v2" {
			target = &cases[i]
			break
		}
	}
	if target == nil {
		t.Fatal("the corpus carries no address_v2 case to tamper with")
	}

	gotPreimage, gotPayload := recomputeDifferential(t, *target)
	if problems := differentialProblems(target.PreimageXDR, target.PayloadHex, gotPreimage, gotPayload); len(problems) > 0 {
		t.Fatalf("the untampered case already disagrees: %v", problems)
	}

	// Flip one hex digit of the recorded payload. Every value is a plausible
	// payload, so only the comparison can tell them apart.
	tampered := []byte(gotPayload)
	if tampered[0] == '0' {
		tampered[0] = '1'
	} else {
		tampered[0] = '0'
	}
	if problems := differentialProblems(target.PreimageXDR, string(tampered), gotPreimage, gotPayload); len(problems) == 0 {
		t.Error("a tampered payload was not detected")
	}
}

// TestDifferentialCorpusCoversEveryArmAndShape is the completeness guard. A
// corpus that quietly stopped generating one arm, or stopped nesting delegates,
// would still pass the comparison above; it would just be testing less. Every
// case the acceptance criteria name is asserted present here.
func TestDifferentialCorpusCoversEveryArmAndShape(t *testing.T) {
	cases := loadDifferentialCorpus(t)

	// The four credentials arms the protocol defines.
	for _, arm := range []string{"source_account", "address", "address_v2", "address_with_delegates"} {
		if !anyCase(cases, func(doc differentialCase) bool { return doc.CredentialArm == arm }) {
			t.Errorf("no %s case in the corpus", arm)
		}
	}

	// At least the four arms, and enough of them that a single lucky case
	// cannot stand in for a shape. Frozen regressions add to the swept corpus,
	// so the floor is on the whole set.
	if len(cases) < 100 {
		t.Errorf("the corpus has %d cases, want at least 100", len(cases))
	}

	var (
		sawCreateContract bool
		maxInvocation     int
		maxDelegates      int
		sawNegative       bool
		sawMax            bool
		sawMin            bool
	)

	for _, doc := range cases {
		entry := decodeDifferentialEntry(t, doc)

		if entry.RootInvocation.Function.Type == xdr.SorobanAuthorizedFunctionTypeSorobanAuthorizedFunctionTypeCreateContractHostFn {
			sawCreateContract = true
		}
		if depth := diffInvocationDepth(entry.RootInvocation, 0); depth > maxInvocation {
			maxInvocation = depth
		}
		if entry.Credentials.Type == xdr.SorobanCredentialsTypeSorobanCredentialsAddressWithDelegates {
			if depth := diffDelegateDepth(entry.Credentials.AddressWithDelegates.Delegates); depth > maxDelegates {
				maxDelegates = depth
			}
		}

		nonce := diffNonce(entry)
		if nonce < 0 {
			sawNegative = true
		}
		if nonce == math.MaxInt64 {
			sawMax = true
		}
		if nonce == math.MinInt64 {
			sawMin = true
		}
	}

	if !sawCreateContract {
		t.Error("no create-contract invocation in the corpus")
	}
	if maxInvocation < 2 {
		t.Errorf("deepest invocation tree is %d levels, want at least 2 (a sub-invocation)", maxInvocation)
	}
	if maxDelegates < 2 {
		t.Errorf("deepest delegate tree is %d levels, want at least 2 (a nested delegate)", maxDelegates)
	}
	if !sawNegative {
		t.Error("no negative nonce in the corpus")
	}
	if !sawMax {
		t.Error("no MaxInt64 nonce in the corpus")
	}
	if !sawMin {
		t.Error("no MinInt64 nonce in the corpus")
	}
}

func anyCase(cases []differentialCase, predicate func(differentialCase) bool) bool {
	for _, doc := range cases {
		if predicate(doc) {
			return true
		}
	}
	return false
}

// diffInvocationDepth is the height of a call tree, with a bare call at 1.
func diffInvocationDepth(invocation xdr.SorobanAuthorizedInvocation, depth int) int {
	max := depth + 1
	for _, sub := range invocation.SubInvocations {
		if d := diffInvocationDepth(sub, depth+1); d > max {
			max = d
		}
	}
	return max
}

// diffDelegateDepth is the height of a delegates array, empty at 0.
func diffDelegateDepth(nodes []xdr.SorobanDelegateSignature) int {
	max := 0
	for i := range nodes {
		if d := 1 + diffDelegateDepth(nodes[i].NestedDelegates); d > max {
			max = d
		}
	}
	return max
}

// diffNonce reads the nonce off whichever address arm the entry uses. A
// source-account entry has none, and 0 is the honest answer for it.
func diffNonce(entry xdr.SorobanAuthorizationEntry) int64 {
	switch entry.Credentials.Type {
	case xdr.SorobanCredentialsTypeSorobanCredentialsAddress:
		if entry.Credentials.Address != nil {
			return int64(entry.Credentials.Address.Nonce)
		}
	case xdr.SorobanCredentialsTypeSorobanCredentialsAddressV2:
		if entry.Credentials.AddressV2 != nil {
			return int64(entry.Credentials.AddressV2.Nonce)
		}
	case xdr.SorobanCredentialsTypeSorobanCredentialsAddressWithDelegates:
		if entry.Credentials.AddressWithDelegates != nil {
			return int64(entry.Credentials.AddressWithDelegates.AddressCredentials.Nonce)
		}
	}
	return 0
}
