package soroauth

import (
	"bytes"
	"crypto/ecdsa"
	"crypto/elliptic"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"math/big"
	"os"
	"path/filepath"
	"testing"

	"github.com/stellar/go-stellar-sdk/xdr"
)

// passkeyReferenceLibrary is the exact reference build the passkey vectors must
// come from. The passkey signature shape is not protocol-defined — a custom
// account's __check_auth decides it — so unlike the authorization-entry
// vectors there is no CAP to cite. This constant names the real wallet library
// the shape is reproduced from instead; a vector from any other build is not
// evidence about this one.
const passkeyReferenceLibrary = "smart-account-kit@0.8.0"

// passkeyVector is one recorded passkey signature-shape case, as written by
// testdata/gen/gen-passkey.mjs.
type passkeyVector struct {
	SchemaVersion int    `json:"schema_version"`
	Name          string `json:"name"`
	Library       string `json:"library"`
	XDRSDK        string `json:"xdr_sdk"`
	// PublicKeyHex is the credential's P-256 public key in uncompressed SEC1
	// form (0x04 || X || Y, 65 bytes).
	PublicKeyHex string `json:"public_key_hex"`
	// SignatureHex is the fixed-width r || s signature (64 bytes, each scalar
	// left-padded to 32).
	SignatureHex string `json:"signature_hex"`
	// SignatureMapXDR is the {public_key, signature} ScMap the reference
	// library built for this key and signature. It is taken out of the
	// library's own output, not rebuilt here, and is what
	// Secp256r1SignatureScVal must reproduce byte-for-byte.
	SignatureMapXDR string `json:"signature_map_xdr"`
	// LibraryScValXDR is the library's complete return value: the signature map
	// wrapped in a one-element vector.
	LibraryScValXDR string `json:"library_scval_xdr"`
}

// loadPasskeyVectors reads every committed passkey vector. Like the entry
// vectors, unknown fields are rejected and the reference version is checked, so
// a schema change or a vector from another library fails rather than being
// silently half-read.
func loadPasskeyVectors(t testing.TB) []passkeyVector {
	t.Helper()

	paths, err := filepath.Glob(filepath.Join("testdata", "vectors", "passkey", "*.json"))
	if err != nil {
		t.Fatalf("globbing the passkey vector directory: %v", err)
	}
	// Without this, deleting every passkey vector would turn this file into a
	// test that passes by doing nothing.
	if len(paths) == 0 {
		t.Fatal("no passkey vectors found in testdata/vectors/passkey; run `cd testdata/gen && npm ci && node gen-passkey.mjs`")
	}

	vectors := make([]passkeyVector, 0, len(paths))
	for _, path := range paths {
		raw, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("reading %s: %v", path, err)
		}
		var v passkeyVector
		decoder := json.NewDecoder(bytes.NewReader(raw))
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&v); err != nil {
			t.Fatalf("decoding %s: %v", path, err)
		}
		if v.SchemaVersion != 1 {
			t.Fatalf("%s has unsupported schema version %d, want 1", path, v.SchemaVersion)
		}
		if v.Library != passkeyReferenceLibrary {
			t.Fatalf("%s was generated by %q, want %q", path, v.Library, passkeyReferenceLibrary)
		}
		if v.Name == "" {
			t.Fatalf("%s has no name", path)
		}
		vectors = append(vectors, v)
	}
	return vectors
}

// passkeyPublicKey turns the recorded uncompressed SEC1 bytes back into an
// ecdsa.PublicKey, which is the form Secp256r1SignatureScVal takes.
func passkeyPublicKey(v passkeyVector) (*ecdsa.PublicKey, error) {
	raw, err := hex.DecodeString(v.PublicKeyHex)
	if err != nil {
		return nil, fmt.Errorf("decoding public_key_hex: %w", err)
	}
	if len(raw) != Secp256r1PublicKeySize {
		return nil, fmt.Errorf("public key is %d bytes, want %d", len(raw), Secp256r1PublicKeySize)
	}
	if raw[0] != 0x04 {
		return nil, fmt.Errorf("public key prefix is 0x%02x, want 0x04 (uncompressed SEC1)", raw[0])
	}
	return &ecdsa.PublicKey{
		Curve: elliptic.P256(),
		X:     new(big.Int).SetBytes(raw[1:33]),
		Y:     new(big.Int).SetBytes(raw[33:65]),
	}, nil
}

// verifyPasskeyVector returns an error when soroauth does not reproduce the
// recorded vector byte-for-byte. It returns an error rather than failing the
// test so that TestPasskeyVectorComparisonRejectsATamperedVector can prove the
// check actually bites.
//
// Two things are asserted, and they are different claims:
//
//  1. Secp256r1SignatureScVal builds exactly the map the reference library
//     built, byte for byte — its key order ("public_key" before "signature",
//     the host's sort order), the symbol encoding, and the fixed-width byte
//     encodings of both values.
//  2. The library's complete return value is exactly that map wrapped in a
//     one-element vector. This pins the relationship the vectors describe, so
//     the recorded reference cannot silently become a different shape.
func verifyPasskeyVector(v passkeyVector) error {
	publicKey, err := passkeyPublicKey(v)
	if err != nil {
		return err
	}
	signature, err := hex.DecodeString(v.SignatureHex)
	if err != nil {
		return fmt.Errorf("decoding signature_hex: %w", err)
	}

	got, err := Secp256r1SignatureScVal(publicKey, signature)
	if err != nil {
		return fmt.Errorf("building the signature ScVal: %w", err)
	}
	gotBytes, err := got.MarshalBinary()
	if err != nil {
		return fmt.Errorf("marshalling the signature ScVal: %w", err)
	}

	wantMap, err := base64.StdEncoding.DecodeString(v.SignatureMapXDR)
	if err != nil {
		return fmt.Errorf("decoding signature_map_xdr: %w", err)
	}
	if !bytes.Equal(gotBytes, wantMap) {
		return fmt.Errorf("%s: signature map differs from %s\n want %x\n  got %x",
			v.Name, v.Library, wantMap, gotBytes)
	}

	// The reference wraps the map in a one-element vector. Rebuilding that here
	// from the Go value, rather than trusting the recorded bytes, is what makes
	// the second claim a real comparison.
	wantFull, err := base64.StdEncoding.DecodeString(v.LibraryScValXDR)
	if err != nil {
		return fmt.Errorf("decoding library_scval_xdr: %w", err)
	}
	var recorded xdr.ScVal
	if err := recorded.UnmarshalBinary(wantFull); err != nil {
		return fmt.Errorf("decoding library_scval_xdr as an ScVal: %w", err)
	}
	if recorded.Type != xdr.ScValTypeScvVec {
		return fmt.Errorf("%s: the reference ScVal is %s, want a vector", v.Name, recorded.Type)
	}
	// xdr.ScVal holds the vector as a pointer to a pointer, so dereference both
	// to reach the element slice.
	if recorded.Vec == nil || *recorded.Vec == nil {
		return fmt.Errorf("%s: the reference vector is empty", v.Name)
	}
	if elements := **recorded.Vec; len(elements) != 1 {
		return fmt.Errorf("%s: the reference vector holds %d elements, want 1", v.Name, len(elements))
	}
	wrapped, err := scVec(got).MarshalBinary()
	if err != nil {
		return fmt.Errorf("marshalling the wrapped signature ScVal: %w", err)
	}
	if !bytes.Equal(wrapped, wantFull) {
		return fmt.Errorf("%s: the reference ScVal is not scvVec([the signature map])\n want %x\n  got %x",
			v.Name, wantFull, wrapped)
	}
	return nil
}

// TestPasskeyGoldenVectors is the correctness gate for the passkey signature
// shape: for every recorded case, soroauth must build the same bytes the pinned
// smart-account-kit built for the same key and signature.
//
// Scope, stated so the passing test is not read as more than it is: these
// vectors prove the *encoding* of the signature map. The scalars in them are
// fixed shape inputs, not a signature over any message — an ECDSA signature is
// randomised, so a byte-reproducible vector cannot carry a fresh one. That the
// P-256 signing and verification primitives produce and accept real signatures
// is covered separately in secp256r1_test.go.
func TestPasskeyGoldenVectors(t *testing.T) {
	for _, v := range loadPasskeyVectors(t) {
		t.Run(v.Name, func(t *testing.T) {
			if err := verifyPasskeyVector(v); err != nil {
				t.Error(err)
			}
		})
	}
}

// TestPasskeyVectorsCoverTheRequiredCases guards the set itself: a vector that
// is deleted, or never generated, must fail the build rather than quietly
// shrink the gate.
func TestPasskeyVectorsCoverTheRequiredCases(t *testing.T) {
	required := []string{
		"passkey_signature_map_typical",
		"passkey_signature_map_min_scalars",
		"passkey_signature_map_max_scalars",
		"passkey_signature_map_leading_zero_scalar",
		"passkey_signature_map_high_bit_key",
		"passkey_signature_map_leading_zero_key_byte",
	}

	present := map[string]bool{}
	for _, v := range loadPasskeyVectors(t) {
		present[v.Name] = true
	}
	for _, name := range required {
		if !present[name] {
			t.Errorf("required passkey vector %q is missing", name)
		}
	}
	if len(present) != len(required) {
		t.Errorf("%d passkey vectors are committed, want the %d named ones", len(present), len(required))
	}
}

// TestPasskeyVectorsExerciseTheEdgeBytes asserts that the edge cases the vector
// names actually appear in the recorded material. A vector whose name claims a
// leading zero scalar but whose bytes do not have one would still pass the
// byte-identity test while proving nothing about padding.
func TestPasskeyVectorsExerciseTheEdgeBytes(t *testing.T) {
	t.Run("min scalars are left-padded", func(t *testing.T) {
		v := findPasskeyVector(t, "passkey_signature_map_min_scalars")
		sig, err := hex.DecodeString(v.SignatureHex)
		if err != nil {
			t.Fatalf("decoding signature_hex: %v", err)
		}
		if len(sig) != Secp256r1SignatureSize {
			t.Fatalf("signature is %d bytes, want %d", len(sig), Secp256r1SignatureSize)
		}
		for i, b := range sig[:31] {
			if b != 0x00 {
				t.Fatalf("r byte %d is 0x%02x, want 0x00: the scalar is not minimal", i, b)
			}
		}
		if sig[31] != 0x01 || sig[63] != 0x01 {
			t.Fatalf("scalar bytes are 0x%02x and 0x%02x, want 0x01", sig[31], sig[63])
		}
	})

	t.Run("max scalars set every byte", func(t *testing.T) {
		v := findPasskeyVector(t, "passkey_signature_map_max_scalars")
		sig, err := hex.DecodeString(v.SignatureHex)
		if err != nil {
			t.Fatalf("decoding signature_hex: %v", err)
		}
		if sig[0] != 0xff {
			t.Fatalf("r's top byte is 0x%02x, want 0xff", sig[0])
		}
	})

	t.Run("leading zero scalar has a zero top byte", func(t *testing.T) {
		v := findPasskeyVector(t, "passkey_signature_map_leading_zero_scalar")
		sig, err := hex.DecodeString(v.SignatureHex)
		if err != nil {
			t.Fatalf("decoding signature_hex: %v", err)
		}
		if sig[0] != 0x00 {
			t.Fatalf("r's top byte is 0x%02x, want 0x00 (the padding case)", sig[0])
		}
	})

	t.Run("high bit key sets the top bits", func(t *testing.T) {
		v := findPasskeyVector(t, "passkey_signature_map_high_bit_key")
		raw, err := hex.DecodeString(v.PublicKeyHex)
		if err != nil {
			t.Fatalf("decoding public_key_hex: %v", err)
		}
		if raw[1]&0x80 == 0 || raw[33]&0x80 == 0 {
			t.Fatalf("key bytes are 0x%02x and 0x%02x, want the high bit set in both", raw[1], raw[33])
		}
	})

	t.Run("leading zero key byte is padded", func(t *testing.T) {
		v := findPasskeyVector(t, "passkey_signature_map_leading_zero_key_byte")
		raw, err := hex.DecodeString(v.PublicKeyHex)
		if err != nil {
			t.Fatalf("decoding public_key_hex: %v", err)
		}
		if len(raw) != Secp256r1PublicKeySize {
			t.Fatalf("key is %d bytes, want %d", len(raw), Secp256r1PublicKeySize)
		}
		if raw[1] != 0x00 {
			t.Fatalf("X's top byte is 0x%02x, want 0x00 (the padding case)", raw[1])
		}
	})
}

// TestPasskeyVectorComparisonRejectsATamperedVector proves the byte-identity
// check bites. A comparison that could not fail would be evidence of nothing,
// so here a real vector is altered and the check must notice.
func TestPasskeyVectorComparisonRejectsATamperedVector(t *testing.T) {
	original := findPasskeyVector(t, "passkey_signature_map_typical")

	t.Run("a flipped signature byte", func(t *testing.T) {
		tampered := original
		sig, err := hex.DecodeString(tampered.SignatureHex)
		if err != nil {
			t.Fatalf("decoding signature_hex: %v", err)
		}
		sig[0] ^= 0xff
		tampered.SignatureHex = hex.EncodeToString(sig)
		if err := verifyPasskeyVector(tampered); err == nil {
			t.Fatal("the comparison accepted a signature that differs from the reference")
		}
	})

	t.Run("a reordered signature map", func(t *testing.T) {
		tampered := original
		// The recorded map's key order is public_key before signature. Swapping
		// the two entries is the exact mistake an unsorted hand-built map
		// makes, so the check has to reject it.
		mapBytes, err := base64.StdEncoding.DecodeString(tampered.SignatureMapXDR)
		if err != nil {
			t.Fatalf("decoding signature_map_xdr: %v", err)
		}
		var value xdr.ScVal
		if err := value.UnmarshalBinary(mapBytes); err != nil {
			t.Fatalf("decoding the signature map: %v", err)
		}
		entries := **value.Map
		entries[0], entries[1] = entries[1], entries[0]
		swapped, err := value.MarshalBinary()
		if err != nil {
			t.Fatalf("marshalling the swapped map: %v", err)
		}
		tampered.SignatureMapXDR = base64.StdEncoding.EncodeToString(swapped)
		if err := verifyPasskeyVector(tampered); err == nil {
			t.Fatal("the comparison accepted a map with its keys out of order")
		}
	})
}

func findPasskeyVector(t *testing.T, name string) passkeyVector {
	t.Helper()
	for _, v := range loadPasskeyVectors(t) {
		if v.Name == name {
			return v
		}
	}
	t.Fatalf("passkey vector %q is missing", name)
	return passkeyVector{}
}
